book/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'book'
urlpatterns = [
    path('', views.home, name='home'),
    path('vehicles/<slug>/', views.vehicle_list, name='vehicle_list'),
    path('vehicle/<slug>/', views.vehicle_detail, name='vehicle_detail'),
    path('complaint/', views.complaint_list, name='complaint_list'),
    path('complaint/<int:id>/', views.complaint_detail, name='complaint_detail'),
    path('complaint/edit/<int:id>/', views.edit_complaint, name='edit_complaint'),
    path('fault/<int:id>/', views.fault_detail, name='fault_detail'),
    path('complaint/add/', views.add_complaint, name='add_complaint'),
    path('fault/', views.fault_list, name='fault_list'),
    path('fault/edit/<int:id>/', views.edit_fault, name='edit_fault'),
    path('inspection/', views.inspection_list, name='inspection_list'),
    path('inspection/<int:id>/', views.inspection_detail, name='inspection_detail'),
    path('export/', views.export_complaints_xls, name='export_complaints_xls'),
    path('fault_without_complaint/<int:id>/', views.fault_without_complaint_detail,
         name='fault_without_complaint_detail'),
    path('fault_without_complaint/', views.fault_without_complaint_list, name='fault_without_complaint_list'),
    path('fault_without_complaint/add/', views.add_fault_without_complaint, name='add_fault_without_complaint'),
    path('fault_without_complaint/edit/<int:id>/', views.edit_fault_without_complaint,
         name='edit_fault_without_complaint'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from book import views

import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.CustomPasswordChangeView.as_view(),
         name='change_password'),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/change_password_done.html'),
         name='password_change_done'),
    path('', include('book.urls')),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings

import datetime, os

vehicle_choices = (
        ('SA132', 'SA132'),
        ('SA133', 'SA133'),
        ('SA134', 'SA134'),
        ('SA136', 'SA136'),
        ('SA139', 'SA139'),
)


def user_directory_path(instance, file_name):
    return 'complaint_{0}/{1}'.format(instance.complaint.id, file_name)


class Owner(models.Model):
    name = models.CharField(max_length=20,
                            unique=True)
    slug = models.CharField(max_length=20)
    city = models.CharField(max_length=30)
    address = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    @property
    def create_image_path(self):
        img_path = 'book/{}.jpeg'.format(self.name)
        return img_path

class Trolleys(models.Model):
    name = models.CharField(max_length=10,
                            unique=True)
    first = models.CharField(max_length=20,
                             unique=True)
    second = models.CharField(max_length=20,
                              unique=True)
    third = models.CharField(max_length=20,
                             blank=True,
                             unique=True,
                             null=True)
    fourth = models.CharField(max_length=20,
                              blank=True,
                              unique=True,
                              null=True)
    fifth = models.CharField(max_length=20,
                             blank=True,
                             unique=True,
                             null=True)
    sixth = models.CharField(max_length=20,
                             blank=True,
                             unique=True,
                             null=True)
    seventh = models.CharField(max_length=20,
                               blank=True,
                               unique=True,
                               null=True)
    eighth = models.CharField(max_length=20,
                              blank=True,
                              unique=True,
                              null=True)
    ninth = models.CharField(max_length=20,
                             blank=True,
                             unique=True,
                             null=True)

    def __str__(self):
        return self.name


class Vehicle(models.Model):
    number = models.CharField(max_length=10)
    vehicle_type = models.CharField(max_length=10,
                                    db_index=True,
                                    choices=vehicle_choices)
    slug = models.SlugField(max_length=20,
                            db_index=True,
                            unique=True)
    trolleys = models.OneToOneField(Trolleys,
                                 related_name='vehicle_trolleys',
                                 on_delete=models.CASCADE)
    warranty = models.DateField()
    owner = models.ForeignKey(Owner,
                              related_name='owners',
                              on_delete=models.CASCADE,
                              db_index=True)

    class Meta:
        ordering = ('vehicle_type', 'number')

    def __str__(self):
        return 'Pojazd: {}-{}'.format(self.vehicle_type, self.number)

    @property
    def get_full_name(self):
        return '{}-{}'.format(self.vehicle_type, self.number)

    def is_warrenty(self, date=None):
        if date:
            today = date
        else:
            today = datetime.date.today()
        if self.warranty >= today:
            return True
        else:
            return False

    # def get_absolute_url(self):
    #     return reverse('book:vehicle_detail',
    #                    args=[self.id, self.slug])


class Inspection(models.Model):
    choices = (
        ('P1.1', 'P1.1'),
        ('P1.2', 'P1.2'),
        ('P1.3', 'P1.3'),
        ('P2.1', 'P2.1'),
        ('P2.2', 'P2.2'),
        ('P2.3', 'P2.3'),
        ('P3.1', 'P3.1'),
        ('P3.2', 'P3.2'),
    )
    date = models.DateField()
    inspection_type = models.CharField(max_length=10,
                                       db_index=True,
                                       choices=choices)
    performer = models.CharField(max_length=30,
                                 db_index=True)
    vehicle = models.ForeignKey(Vehicle,
                                related_name='vehicles',
                                on_delete=models.CASCADE)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return 'Przegląd: {}, dzień wykonania: {}.{}.{}'.format(self.inspection_type, self.date.day, self.date.month,
                                                                self.date.year)


class Complaint(models.Model):
    status_choices = (
        ('open', 'Otwarta'),
        ('close', 'Zamknięta')
    )
    published_date = models.DateTimeField(auto_now_add=True)
    document_number = models.CharField(max_length=50,
                                       unique=True)
    entry_date = models.DateField()
    updated = models.DateField(auto_now=True)
    end_date = models.DateField(blank=True,
                                    null=True)
    status = models.CharField(max_length=10,
                              choices=status_choices)
    tasks = models.TextField(blank=True,
                             null=True)
    client = models.ForeignKey(Owner,
                               related_name='owners_complaint',
                               on_delete=models.CASCADE,
                               db_index=True)
    vehicle = models.ForeignKey(Vehicle,
                                related_name='complaint_vehicles',
                                on_delete=models.CASCADE)
    author = models.ForeignKey(User,
                               related_name='auth_complaint',
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True)

    def __str__(self):
        return self.document_number

    class Meta:
        ordering = ('-entry_date',)

    @property
    def day_counter(self):
        days = datetime.date.today() - self.entry_date
        return days.days


class File(models.Model):
    complaint = models.ForeignKey(Complaint,
                                  related_name='files_complaint',
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True
                                  )
    file_document = models.FileField(upload_to=user_directory_path,
                            blank=True,
                            null=True)

    @property
    def get_path(self):
        return os.path.join(settings.MEDIA_ROOT, self.file_document.url)


class Fault(models.Model):
    status_choices = (
        ('open', 'Otwarta'),
        ('close', 'Zamknięta')
    )
    category_choices = (
        ('pudło', (
            ('nadwozie', 'Nadwozie'),
            ('poszycie', 'Poszycie'),
            ('podłoga', 'Podłoga'),
            ('konstrukcja', 'Konstrukcja'),
            ('układy nośne', 'Układy nośne'),
            ('grodzenia', 'Grodzenia'),
        )),
        ('materiały wykończeniowe', (
            ('malatura', 'Malatura'),
            ('kalkomania', 'Kalkomania'),
        )),
        ('wyposażnie wewn.', 'Wyposażenie wewnętrzne'),
        ('wózek', 'Wózek'),
        ('urządz. ster. pojazdem', 'Urządzenia sterujące pojazdem'),
        ('urządz, monitoringu i bezpiecz.', 'Urządzenia monitoringu i bezpieczeństwa'),
        ('klima i orzewanie', 'Klimatyzacja i ogrzewanie'),
        ('drzwi', 'Drzwi'),
        ('sip', 'Urządzenia informacyjne'),
        ('układ hamowania', 'Układ hamowania'),
        ('układ sprzęgania', 'Układ sprzęgania'),
        ('okna i szyby', 'Okna i szyby'),
        ('układ elek.', 'Układ elektryczny'),
        ('Układ napędowy', (
            ('silnik', 'Silnik'),
            ('przekładnia', 'Przekładnia'),
        )),
        ('Wyposażenie zewnętrzne', (
            ('wycieraczki', 'Wycieraczki'),
            ('lusterka', 'Lusterka'),
            ('syreny', 'Syreny'),
        )),
        ('układ pneumatyczny', 'Układ pneumatyczny'),
    )
    name = models.CharField(max_length=40)
    category = models.CharField(max_length=50,
                                db_index=True,
                                choices=category_choices)
    description = models.TextField()
    actions = models.TextField(blank=True)
    comments = models.TextField(blank=True)
    zr_number = models.CharField(max_length=10,
                                 unique=True,
                                 blank=True,
                                 null=True)
    status = models.CharField(max_length=10,
                              choices=status_choices)
    entry_date = models.DateField()
    end_date = models.DateField(blank=True,
                                null=True)
    need = models.TextField(blank=True)
    complaint = models.ForeignKey(Complaint,
                                  related_name='complaint_faults',
                                  on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle,
                                related_name='vehicle_faults',
                                on_delete=models.CASCADE)

    class Meta:
        ordering = ('-entry_date',)

    def __str__(self):
        return self.name


class Fault_without_complaint(models.Model):
    status_choices = (
        ('open', 'Otwarta'),
        ('close', 'Zamknięta')
    )
    category_choices = (
        ('pudło', (
            ('nadwozie', 'Nadwozie'),
            ('poszycie', 'Poszycie'),
            ('podłoga', 'Podłoga'),
            ('konstrukcja', 'Konstrukcja'),
            ('układy nośne', 'Układy nośne'),
            ('grodzenia', 'Grodzenia'),
        )),
        ('materiały wykończeniowe', (
            ('malatura', 'Malatura'),

book/templates/book/complaint/add.html
{% extends "book/base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
{{ form_complaint.media }}
<div class="container">
  <h3>Dodaj reklamację</h3>
  <form enctype="multipart/form-data" action="/complaint/add/?number={{ request.GET.number }}" method="POST">
    {% csrf_token %}
    {{ form_complaint|crispy }}
      <h4>Usterki</h4><br>
      {{ formset_fault|crispy }}
    <button type="submit" class="btn btn-primary">Zapisz</button>
  </form>
</div>
{% endblock %}

book/templates/book/complaint/detail.html
{% extends "book/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    {% if complaint %}
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Reklamacja</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Klient</th>
          <td>{{ complaint.client.name }}</td>
        </tr>
        <tr>
          <th scope="row">Pojazd</th>
          <td>{{ complaint.vehicle.get_full_name }}</td>
        </tr>
        <tr>
          <th scope="row">Nr reklamacji</th>
          <td>{{ complaint }}</td>
        </tr>
        <tr>
          <th scope="row">Data wystawienia</th>
          <td>{{ complaint.entry_date|date:"d-m-Y" }}</td>
        </tr>
        <tr>
          <th scope="row">Status</th>
          <td>{{ complaint.get_status_display }}</td>
        </tr>
        {% if complaint.status == 'close' %}
          <tr>
            <th scope="row">Data zamknięcia</th>
            <td>{{ complaint.end_date|date:'d-m-Y' }}</td>
          </tr>
        {% endif %}
        {% if complaint.files_complaint %}
          {% for f in complaint.files_complaint.all %}
            <tr>
              <th scope="row">Załączniki</th>
              <td><a href="{{ f.get_path }}">{{ f.file_document.url }}</a></td>
            </tr>
          {% endfor %}
        {% endif %}
        <tr>
          <th scope="row"><a href="{% url 'book:edit_complaint' complaint.id %}">Edytuj reklamację</a></th>
          <td></td>
        </tr>
      </tbody>
    </table>
    {% endif %}
    {% if complaint.complaint_faults %}
      {% for fault in complaint.complaint_faults.all %}
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col">{{ fault.name }}</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">Numer ZR</th>
              {% if fault.zr_number == None %}
                <td></td>
              {% else %}
                <td>{{ fault.zr_number }}</td>
              {% endif %}
            </tr>
            <tr>
              <th scope="row">Status</th>
              <td>{{ fault.get_status_display }}</td>
            </tr>
            {% if fault.status == 'close' %}
            <tr>
              <th scope="row">Data zamknięcia</th>
              <td>{{ fault.end_date|date:'d-m-Y' }}</td>
            </tr>
            {% endif %}
            <tr>
              <th scope="row">Opis</th>
              <td>{{ fault.description }}</td>
            </tr>
            <tr>
              <th scope="row">Podjęte działania</th>
              <td>{{ fault.actions }}</td>
            </tr>
            <tr>
              <th scope="row">Uwagi</th>
              <td>{{ fault.comments }}</td>
            </tr>
            <tr>
              <th scope="row">Potrzeby</th>
              <td>{{ fault.need }}</td>
            </tr>
            <tr>
              <th scope="row"><a href="{% url 'book:edit_fault' fault.id %}">Edytuj usterkę</a></th>
              <td></td>
            </tr>
          </tbody>
        </table>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

book/templates/book/complaint/edit.html
{% extends "book/base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
{{ form.media }}
<div class="container">
  <h3>Edytuj reklamację</h3>
  <form enctype="multipart/form-data" action="{% url 'book:edit_complaint' complaint.id %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Zapisz</button>
  </form>
</div>
{% endblock %}

book/templates/book/complaint/list.html
{% extends "book/base.html" %}

{% load crispy_forms_tags %}
{% load mathfilters %}
{% load book_extras %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
{{ form.media }}
<div class="container pb-3">
  {% if complaints %}
  <form action="." method="GET" class="form-inline">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Szukaj">
  </form>
  <form action="{% url 'book:add_complaint' %}" method="GET" class="form-inline">
    <!-- {% csrf_token %} -->
    {{ form_add_complaint|crispy }}
    <input type="submit" value="Dodaj reklamację">
  </form>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="align-middle text-center">Lp</th>
        <th scope="col" class="align-middle text-center">Nr dokumentu</th>
        <th scope="col" class="align-middle text-center">Pojazd</th>
        <th scope="col" class="align-middle text-center">Data wejścia</th>
        <th scope="col" class="align-middle text-center">Data zakończenia</th>
        <th scope="col" class="align-middle text-center">Dni</th>
        <th scope="col" class="align-middle text-center">Usterka</th>
      </tr>
    </thead>
    <tbody>
      {% for complaint in complaints %}
      <tr>
        <th scope="row" class="text-center">{{ forloop.counter|add:pages }}</th>
        {% if complaint.status == 'close' %}
          <td class="text-center"><a class="text-success" href="{% url 'book:complaint_detail' complaint.id %}">{{ complaint.document_number }}</a></td>
        {% else %}
          <td class="text-center"><a class="text-danger" href="{% url 'book:complaint_detail' complaint.id %}">{{ complaint.document_number }}</a></td>
        {% endif %}
        <td class="text-center">{{ complaint.vehicle.get_full_name }}</td>
        <td class="text-center">{{ complaint.entry_date|date:"d-m-Y" }}</td>
        <td class="text-center">{{ complaint.end_date|date:"d-m-Y" }}</td>
        {% if complaint.status == 'open' %}
          {% if complaint.day_counter >= 3 and complaint.day_counter <= 6 %}
            <td class="text-center text-warning">{{ complaint.day_counter }}</td>
          {% elif complaint.day_counter > 6 %}
            <td class="text-center text-danger">{{ complaint.day_counter }}</td>
          {% else %}
            <td class="text-center">{{ complaint.day_counter }}</td>
          {% endif %}
        {% else %}
          <td class="text-center"></td>
        {% endif %}
        <td>
          <ul>
            {% for fault in complaint.complaint_faults.all %}
            <li>{{ forloop.counter }}.{{ fault.name }} - {{ fault.get_status_display }}</li>
            {% endfor %}
          </ul>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <span class="mr-4">Strona {{ complaints.number }}/{{ paginator.num_pages }}</span>
  {% if complaints.has_previous %}
    {% if complaints.has_previous != 1 %}
      <a href="?page=1">1</a>
    {% endif %}
      <a class="btn btn-dark ml-1" href='{{"?page="|addstr:complaints.previous_page_number|addstr:url_path }}' role="button">{{ complaints.previous_page_number }}</a>
    {% endif %} {% if complaints.has_next %}
      <a class="btn btn-dark ml-1" href='{{"?page="|addstr:complaints.next_page_number|addstr:url_path }}'   role="button">{{ complaints.next_page_number }}</a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}