book/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'book'
urlpatterns = [
    path('', views.home, name='home'),
    path('vehicles/<slug>/', views.vehicle_list, name='vehicle_list'),
    path('vehicle/<slug>/', views.vehicle_detail, name='vehicle_detail'),
    path('complaint/', views.complaint_list, name='complaint_list'),
    path('complaint/<int:id>/', views.complaint_detail, name='complaint_detail'),
    path('complaint/edit/<int:id>/', views.edit_complaint, name='edit_complaint'),
    path('fault/<int:id>/', views.fault_detail, name='fault_detail'),
    path('complaint/add/', views.add_complaint, name='add_complaint'),
    path('fault/', views.fault_list, name='fault_list'),
    path('fault/edit/<int:id>/', views.edit_fault, name='edit_fault'),
    path('inspection/', views.inspection_list, name='inspection_list'),
    path('inspection/<int:id>/', views.inspection_detail, name='inspection_detail'),
    path('export/', views.export_complaints_xls, name='export_complaints_xls'),
    path('fault_without_complaint/<int:id>/', views.fault_without_complaint_detail,
         name='fault_without_complaint_detail'),
    path('fault_without_complaint/', views.fault_without_complaint_list, name='fault_without_complaint_list'),
    path('fault_without_complaint/add/', views.add_fault_without_complaint, name='add_fault_without_complaint'),
    path('fault_without_complaint/edit/<int:id>/', views.edit_fault_without_complaint,
         name='edit_fault_without_complaint'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from book import views

import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password/', views.CustomPasswordChangeView.as_view(),
         name='change_password'),
    path('change_password_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/change_password_done.html'),
         name='password_change_done'),
    path('', include('book.urls')),
]

book/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Owner, Vehicle, Complaint, Fault, Inspection, File, Fault_without_complaint
from django.core.paginator import Paginator
from .forms import FilterComplaintsForm, FilterFaultForm, AddComplaintForm, AddFaultForm, NumberOfFaults, \
    EditFaultForm, EditComplaintForm, FilterFaultWithoutComplaintForm, EditFaultWithoutComplaintForm, \
    AddFaultWithoutComplaintForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView

import xlwt, datetime, magic


def paginator_get_page(models_list, num, page):
    paginator = Paginator(models_list, num)
    return paginator.get_page(page)

def page_counter(page):
    if page != 1:
        page = (page -1) * 10
    else:
        page = 0
    return page

def email(tab, sub, body):
    subject = sub
    email_from = settings.EMAIL_HOST_USER
    recipient_list = tab

    email = EmailMessage(subject=subject, body=body, from_email=email_from, to=recipient_list)
    email.content_subtype = 'html'
    email.send(fail_silently=False)
    return True

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/change_password.html'

    success_url = '/'

    def form_valid(self, form):
        messages.success(self.request, 'Nowe hasło zostało zapisane')
        return super().form_valid(form)


@login_required()
def home(request):
    owners = Owner.objects.all()
    return render(request,
                  template_name='book/index.html',
                  context={'title': 'Książka serwisowa',
                           'owners': owners})

@login_required()
def vehicle_list(request, slug):
    owner = get_object_or_404(Owner, slug=slug)
    return render(request,
                  template_name='book/vehicle/list.html',
                  context={'title': owner.name,
                           'owner': owner})

@login_required()
def vehicle_detail(request, slug):
    vehicle = get_object_or_404(Vehicle, slug=slug)
    title = '{}-{}'.format(vehicle.vehicle_type, vehicle.number)
    return render(request,
                  template_name='book/vehicle/detail.html',
                  context={'title': title,
                           'vehicle': vehicle})

@login_required()
def complaint_list(request):
    page = request.GET.get('page', None)
    pages = page_counter(int(page)) if page else 0
    complaints_list = Complaint.objects.all()
    form = FilterComplaintsForm(request.GET)
    form_add_complaint = NumberOfFaults()
    url_path = ''
    status = request.GET.get('status', '')
    vehicle = request.GET.get('vehicle', '')
    date_to = request.GET.get('date_to', '')
    date_from = request.GET.get('date_from', '')
    client = request.GET.get('client', '')
    url_path += '&'+'status='+status+'&vehicle='+vehicle+'&date_to='+date_to+'&date_from='+date_from+'&client='+client

    to_close = request.GET.get('to_close')
    if to_close == '1':
        complaints_list = Complaint.objects.all()
        complaints_list = complaints_list.filter(status='open',
                                                 complaint_faults__status='close',
                                                 ).exclude(
            complaint_faults__status='open')
        complaints = paginator_get_page(complaints_list, 10, page)
        return render(request,
                      template_name='book/complaint/list.html',
                      context={'title': 'Reklamacje',
                               'complaints': complaints,
                               'form': form,
                               'form_add_complaint': form_add_complaint,
                               'pages': pages})
    if form.is_valid():
        cd = form.cleaned_data
        data = {}
        if cd['status']:
            complaints_list = complaints_list.filter(status=cd['status'])
            data.update({'status': cd['status']})
        if cd['vehicle']:
            complaints_list = complaints_list.filter(vehicle=cd['vehicle'])
            data.update({'vehicle': cd['vehicle'].id})
        if cd['date_from']:
            complaints_list = complaints_list.filter(entry_date__gte=cd['date_from'])
            data.update({'date_from': cd['date_from']})
        if cd['date_to']:
            complaints_list = complaints_list.filter(entry_date__lte=cd['date_to'])
            data.update({'date_to': cd['date_to']})
        if client:
            complaints_list = complaints_list.filter(client__id=client)
            data.update({'client': client})
        complaints = paginator_get_page(complaints_list, 10, page)
        paginator = Paginator(complaints_list, 10)
        form = FilterComplaintsForm(data=data)
        if len(complaints_list) == 0:
            messages.info(request, 'Brak wyników w bazie danych')
            complaints_list = Complaint.objects.all()
            complaints = paginator_get_page(complaints_list, 10, page)
            paginator = Paginator(complaints_list, 10)
        return render(request,
                      template_name='book/complaint/list.html',
                      context={'title': 'Reklamacje',
                               'complaints': complaints,
                               'form': form,
                               'form_add_complaint': form_add_complaint,
                               'pages': pages,
                               'paginator': paginator,
                               'url_path': url_path})
    complaints = paginator_get_page(complaints_list, 10, page)
    paginator = Paginator(complaints_list, 10)
    return render(request,
                  template_name='book/complaint/list.html',
                  context={'title': 'Reklamacje',
                           'complaints': complaints,
                           'form': form,
                           'form_add_complaint': form_add_complaint,
                           'pages': pages,
                           'paginator': paginator,
                           'url_path': url_path})

@login_required()
def complaint_detail(request, id):
    complaint = get_object_or_404(Complaint, id=id)
    title = complaint.vehicle.get_full_name
    return render(request,
                  template_name='book/complaint/detail.html',
                  context={'title': title,
                           'complaint': complaint})

@login_required()
def fault_detail(request, id):
    fault = get_object_or_404(Fault, id=id)
    title = fault.vehicle.get_full_name
    return render(request,
                  template_name='book/fault/detail.html',
                  context={'title': title,
                           'fault': fault})

@login_required()
def add_complaint(request):
    number_of_faults = int(request.GET.get('number', None))
    AddFaultFormSet = formset_factory(AddFaultForm,
                                      extra=number_of_faults,
                                      max_num=number_of_faults,
                                      validate_min=True)
    if number_of_faults <= 0:
        messages.error(request, 'Liczba usterek musi być większa od 0')
        return redirect(reverse('book:complaint_list'))
    if request.method == 'POST':
        form_complaint = AddComplaintForm(request.POST, request.FILES)
        formset_fault = AddFaultFormSet(request.POST)
        if form_complaint.is_valid() and formset_fault.is_valid():
            complaint = form_complaint.save(commit=False)
            faults = []
            for f in formset_fault:
                form = f.save(commit=False)
                if not form.name and not form.category and not form.description and not form.status:
                    messages.error(request, 'Wprowadź wymagane dane usterki')
                    return render(request,
                                  template_name='book/complaint/add.html',
                                  context={'title': 'Reklamacje',
                                           'form_complaint': form_complaint,
                                           'formset_fault': formset_fault})

                if form.end_date and form.end_date < complaint.entry_date:
                    messages.error(request, 'Data zakończenia usterki nie może być wcześniejsza niż data '
                                           'wpłynięcia reklamacji')
                    return render(request,
                                  template_name='book/complaint/add.html',
                                  context={'title': 'Reklamacje',
                                           'form_complaint': form_complaint,
                                           'formset_fault': formset_fault})

                if form.end_date and complaint.end_date and form.end_date > complaint.end_date:
                    messages.error(request, 'Data zakończenia usterki nie może być późniejsza od daty zamknięcia '
                                           'reklamacji')
                    return render(request,
                                  template_name='book/complaint/add.html',
                                  context={'title': 'Reklamacje',
                                           'form_complaint': form_complaint,
                                           'formset_fault': formset_fault})

                faults.append(form)

            if complaint.end_date or complaint.status == 'close':
                for f in faults:
                    if f.status == 'open':
                        messages.error(request, 'Aby zamknąć reklamację wyszystekie usterki muszą mieć status zamknięty '
                                             'i datę '
                                      'zakończenia')
                        return render(request,

book/templates/book/base.html
<!DOCTYPE html>
<html lang="pl" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 50px">
  <a class="navbar-brand" href="{% url 'book:home' %}">Serwis</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:complaint_list' %}">Reklamacje<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:fault_list' %}">Usterki</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:fault_without_complaint_list' %}">Usterki bez reklamacji</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:inspection_list' %}">Przeglądy</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/complaint/?to_close=1">Do odpisania</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book:export_complaints_xls' %}">Eksportuj</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'change_password' %}">Zmień hasło</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Wyloguj</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
  </header>

  <main role="main">
    {% include 'book/messages.html' %}
    {% block content %}{% endblock %}
  </main>

  <footer class="text-muted">

  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

book/templates/book/index.html
{% extends "book/base.html" %}

{% load static %}
{% load book_extras %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    {% if owners %}
    {% for owner in owners %}
    <div class="col-sm-4 pt-3">
    <div class="card text-center" ">
      <div class="card-body">
        <p class="card-text"></p>
        <a href='{{ "complaint"|addstr:"/?client="|addstr:owner.id }}'><img class="card-img-top" src="{% static owner.create_image_path %}" alt="Card image cap"></a>
        <h4 class="card-title mt-md-5">{{ owner.name }}</h4>
      </div>
    </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

book/templates/book/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}